---
title: "04-functions-questions"
author: "Asmer Asrar Safi"
date: "6/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(PPBDS.data)
```



```{r, prepping data}

# Eduting dataset to remove irrelevant variables

qscores1 <- qscores %>% 
  select(-term, -prof_name, -course_number) 

# Creating a dataset for major courses only, by filtering
# for courses in the government department only. 

gov <- qscores1 %>% 
  filter(department == "GOV") %>% 
  head(13)

# Randomly sampling 19 courses from the qscores1 dataset.
# 19 + 13 is equal to 32. 

qscores2 <- qscores1 %>% 
  sample_n(19)

# join the qscores2 (the other 19 courses she takes) and 
# the GOV major courses she takes by other variables, to form 
# a dataset of 32 courses

joinedgovqs2 <- gov %>% 
  full_join(qscores2, by = c('department', 
                             'enrollment', 
                             'workload',
                             'overall',
                             'course_name'))

# More variations can be added, to accommodate for GENEDs,
# secondaries etc too. 

```




```{r, major}

# For major 

get_gov <- function(x) {
  grepl("GOV", x)
  
}
joinedgovqs2 <- joinedgovqs2 %>% 
  tibble(course_detail = map_chr(department, ~ if_else(get_gov(.), "Concentration", "Other")))

```



```{r, reordering data randomly}

# reordering data

joinedgovqs3 <- sample_n(joinedgovqs2, 32)

joinedgovqs3
```

```{r}





```




